### ISSUE TITLE
Relations auto-fill params

### ISSUE THREAD

**Issue by kentcdodds** [jmdobry/angular-data#256]
Would be way cool if I got this:

```javascript
// User
{
  name: 'User',
  endpoint: 'user',
  relations: {
    belongsTo: {
      Account: {
        parent: true,
        localKey: 'accountId',
        localField: 'account'
      }
    }
  }
}

// Account
{
  name: 'Account',
  endpoint: 'account',
  relations: {
    belongsTo: {
      Partition: {
        parent: true,
        localKey: 'partitionId',
        localField: 'partition'
      }
    }
  }
}

// Partition
{
  name: 'Partition',
  endpoint: 'partition'
}
```

And then I could say:

```javascript
var user = User.get(1);
user.name = 'Jason';
user.DSSave();
```

Currently, however, this doesn't work because it results in a PUT to this URL: `rest/account/:accountId/user/:userId` when it should be `rest/partition/:partitionId/account/:accountId/user/:userId` with the partition in front of it. So everywhere I do this, I have to supply the partitionId as a param.

```javascript
var account = Account.get(user.accountId);
user.DSSave({ params: { partitionId: account.partitionId } });
```

If angular-data could do this for me, that would be so cool :-)

**Comment by jmdobry** [comment]
I think I fixed this in js-data and forgot to close this issue. @kentcdodds Let me know if that's incorrect.
