### ISSUE TITLE
Relations - belongsTo same localField and localKey

### ISSUE THREAD

**Issue by JetFault** [jmdobry/angular-data#281]
I'm using Sails on the backend. The API returns: 
```
{
  id: 3,
  jobs: [
    {
      id: 4,
      user: 3
    }
  ]
}
```
So the user obj will be returned with the loaded jobs. However, when looking at angular data, it tries to recursively inject all relations, so it would try to inject the `user` field in the job. This would wind up calling a `DS.inject('user', 3)` which is not a valid inject call cause `attrs` is required to be an object/array, however it is a number. The reason this seems to happen is because `localField` and `localKey` are the same. However, Sails populates associations onto the model, so populating the user onto a job would return:
```
{
  id: 4,
  user: {
    id: 3
  }
}
```
While a not populated call would return:
```
{
  id: 4,
  user: 3
}
```
So, localField and localKey would have to be the same.

Here is a plunker to show the issue: http://plnkr.co/edit/NxXdAnuwBUzDyY2X9u2Z?p=preview
However, since angular-mock is used, the logs that angular-data is using aren't showing.

There should probably be a check to see if localField is not an object, to just not insert it?

**Comment by jmdobry** [comment]
Does Sails not have a way to change the name of the field to use as the key?

**Comment by drakson** [comment]
I agree on this issue. If you want to use the ORM provided by sails, you must choose: populate relations or use the same relation key as id. It cannot be configured to return user_id for example.

**Comment by jmdobry** [comment]
You could try something like this:

```js
DS.defineResource({
  name: 'job',

  // define the relation as angular-data expects
  relations: {
    belongsTo: {
      user: {
        // in the serialize and deserialize hooks we'll map this properly
        localKey: 'userId',
        localField: 'user'
      }
    }
  }
});

DS.defineResource({
  name: 'user',
  relations: {
    hasMany: {
      job: {
        foreignKey: 'userId',
        localField: 'jobs'
      }
    }
  }
});

DS.defaults.deserialize = function (resourceName, data) {

  // If the API returns the key only, map it to the field angular-data expects
  var Resource = DS.definitions[resourceName];
  if (Resource.relations && Resource.relations.belongsTo) {
    angular.forEach(Resource.relations.belongsTo, function (relations, relationResourceName) {
      angular.forEach(relations, function (relationDef) {
        if (angular.isString(data.data[localField]) || angular.isNumber(data.data[localField])) {
          data.data[localKey] = data.data[localField];
          delete data.data[localField];
        }
      });
    });
  }

  return data.data;
};

DS.defaults.serialize = function (resourceName, data) {

  // If we haven't linked the relation, map the key to the field the API expects
  var Resource = DS.definitions[resourceName];
  if (Resource.relations && Resource.relations.belongsTo) {
    angular.forEach(Resource.relations.belongsTo, function (relations, relationResourceName) {
      angular.forEach(relations, function (relationDef) {
        if (!data[localField] && (angular.isString(data[localKey]) || angular.isNumber(data[localKey]))) {
          data[localField] = data[localKey];
        }
      });
    });
  }

  return data;
};
```

The deserialize and serialize hooks are general, so they'll work for as many relations as have belongsTo relationships.

**Comment by drakson** [comment]
Yeah! It works! Thank you jmdobry, it would never have occurred to me doing that way. :)

**Comment by jmdobry** [comment]
Great!

**Comment by JetFault** [comment]
Is there any way to make this work for `DS.inject`, I inject whenever I get data from sockets/cached data in DOM?

Also, wondering the use case of localKey/Field? To see if it is possible to just not call inject for relations if localField is not an object. https://github.com/jmdobry/angular-data/blob/master/src/datastore/sync_methods/inject.js#L19

**Comment by jmdobry** [comment]
When you get data from sockets/cached data you can reused the logic in my example to map the key to the field angular-data expects.

I also thought of another workaround that might also work for the `inject` case.

Try modifying your `job` resource to have a computed property:

```js
DS.defineResource({
  name: 'job',
  relations: {
    belongsTo: {
      user: {
        localKey: 'userId',
        localField: 'user'
      }
    }
  },
  computed: {
    userId: ['user', function (user) {
      if (angular.isNumber(user) || angular.isString(user)) {
        delete this.user;
        return user;
      }
    }]
  }
});
```

**Comment by JetFault** [comment]
The above 2 methods don't work btw.

Computed: http://plnkr.co/edit/q472POcUs31Evka89hak?p=preview
Serialize/Deserialize: http://plnkr.co/edit/rKvgxjdjpAx22CErGMkW?p=preview

**Comment by JetFault** [comment]
@jmdobry Hey, did you have a chance to look at what I said. Also, I feel like this issue should be re-opened.

**Comment by jmdobry** [comment]
In my example solution I didn't handle the hasMany case, I was hoping you could run with it. My example could be modified to handle the hasMany case. I am very busy. Do you think you could try?

from above:
```js
if (Resource.relations && Resource.relations.belongsTo) {
  // code from my example
} else if (Resource.relations && Resource.relations.hasMany) {
  // you try adding the code to handle this case
}
```

The idiosyncrasies of Sails will not dictate angular-data's API. When the problem is being solved generally, you're guaranteed to find examples that don't fit the general solution.

I understand your suggestion about skipping non-objects–I am just trying to decide between failing silently (your suggestion) and enforcing the pre-conditions set forth by the API.

**Comment by randallmeeker** [comment]
> The idiosyncrasies of Sails

FWIW this also seems to be an idiosyncrasy of mongoose.js as well.
