### ISSUE TITLE
Make the throttle configurable

### ISSUE THREAD

**Issue by jmdobry** [jmdobry/angular-data#283]

**Comment by hardyti** [comment]
Awesome, thanks for doing this!

**Comment by jmdobry** [comment]
@hardyti I just realized that the latest version of angular-data doesn't even have the throttle. What version are you using?

```js
$rootScope.$watch(function () {
  DSUtils.observe.Platform.performMicrotaskCheckpoint();
});
```

**Comment by hardyti** [comment]
Looking at my index.js, it has:

    /**
       * @doc overview
       * @id angular-data
       * @name angular-data
       * @description
       * __Version:__ 1.0.0-rc.1

**Comment by hardyti** [comment]
(I'm looking into whether I can upgrade to 1.4.2 at this point...)

**Comment by jmdobry** [comment]
This latest is [1.5.3](https://github.com/jmdobry/angular-data/releases/tag/1.5.3)

[![Bower version](https://badge.fury.io/bo/angular-data.png)](http://badge.fury.io/bo/angular-data) [![NPM version](https://badge.fury.io/js/angular-data.png)](http://badge.fury.io/js/angular-data)

**Comment by hardyti** [comment]
Ok. FYI, before your post about 1.5.3, I tried 1.4.2 real quick (unpatched)...it still renders Firefox 100% CPU bound for 7 seconds on my initial load of a 50 item cache, but then becomes pretty happy and idle (without my patch to 1.0.0-rc1 it seemed to maintain 100% CPU indefinitely based on the 10ms interval). With a larger cache (93 items) 1.4.2 pegged the CPU core for about 48 seconds, and then was happy.

I'd have to make some sort of similar patch to 1.4.2 (and presumably 1.5.3) still, or just go with my patch to 1.0.0-rc1.

**Comment by jmdobry** [comment]
It should work fine with thousands of items in all major browsers. That's been our experience for the past year at work.

**Comment by hardyti** [comment]
It seems fine with 1.5.3 now, in my latest testing.

**Comment by hardyti** [comment]
Sorry if that was all a hassle and for nought. Things are looking good on my side now with 1.5.3.
