### ISSUE TITLE
linkInverse called by default in findAll

### ISSUE THREAD

**Issue by aikoven** [jmdobry/angular-data#284]
When I do `DS.findAll` I get `DS.linkInverse` unexpectedly called by default due to `options` argument being extended by resource definition object:

```javascript
options = DSUtils._(definition, options);
```
https://github.com/jmdobry/angular-data/blob/master/src/datastore/async_methods/findAll.js#L165

The definition object has proxy method `linkInverse` which travels to `options` and enables linking code inside `DS.inject`:

```javascript
  if (options.linkInverse) {
    if (DS.utils.isArray(injected)) {
      if (injected.length) {
        DS.linkInverse(definition.name, injected[0][definition.idAttribute]);
      }
    } else {
      DS.linkInverse(definition.name, injected[definition.idAttribute]);
    }
  }
```

https://github.com/jmdobry/angular-data/blob/master/src/datastore/sync_methods/inject.js#L281-L289

**Comment by jmdobry** [comment]
Set `linkInverse` on the `options` to `false` when you call `findAll` until I can make a fix.

**Comment by jmdobry** [comment]
@aikoven You must be using an outdated version of angular-data, because I've already fixed this. The latest is [1.5.3](https://github.com/jmdobry/angular-data/releases/tag/1.5.3).

```js
if (options.linkInverse && typeof options.linkInverse === 'boolean') {
    if (DS.utils.isArray(injected)) {
      if (injected.length) {
        DS.linkInverse(definition.name, injected[0][definition.idAttribute]);
      }
    } else {
      DS.linkInverse(definition.name, injected[definition.idAttribute]);
    }
  }
```

**Comment by aikoven** [comment]
Somehow I missed that, thanks!
