### ISSUE TITLE
DS.refresh with item not in data store resolves without data

### ISSUE THREAD

**Issue by elado** [jmdobry/angular-data#289]
https://github.com/jmdobry/angular-data/blob/master/src/datastore/async_methods/refresh.js#L77
function resolves without data.

Would it make sense to always return `DS.find`, even if item isn't on the local DB?

In my app, signing out and in ejects data. So everywhere I use `refresh` results in `undefined`.

**Comment by jmdobry** [comment]
> Would it make sense to always return DS.find, even if item isn't on the local DB?

No. The point of DS.refresh is to only retrieve a fresh copy of data that is already in the store. If it's not in the store, just call DS.find yourself.

**Comment by elado** [comment]
I ended up calling `find` with `bypassCache: true`.
