### ISSUE TITLE
Angular JS Data Status

### ISSUE THREAD

**Issue by demisx** [jmdobry/angular-data#291]
Hi. I've read in the docs that new development should be using `js-data-angular` moving forward. And I also read that v2 is not ready yet. Can you please clarify whether we should use v2 for the new Angular apps or not? My understanding that v2 and JS Data Angular are the same things.

**Comment by jmdobry** [comment]
See my response to [your other comment](https://github.com/jmdobry/angular-data/issues/220#issuecomment-70213907).
