### ISSUE TITLE
loaclStorage create fails without upsert = false

### ISSUE THREAD

**Issue by Hypercubed** [jmdobry/angular-data#297]
This could be user error but I am trying to follow the `DSLocalStorageAdapter.create` example like so:
```
  Users.create({
    id: 1,
    name: 'Bob'
  })
  .then(function(user) {   // doesn't work unless already a user with id = 1
    console.log('Bob', user);  
    user.name = 'Bob Falfa';
    user.DSSave();
  });
```
This does not create a new user unless there is already a user with id = 1. However, if I set the `upsert` option to false it works.  I would also think that a simple `Users.createInstance` followed by a `DDSave` would work.  Again, maybe I am missing something.  Here is a plunk: http://plnkr.co/edit/racN0A?p=preview

**Comment by jmdobry** [comment]
I tried angular-data-1.5.3.js instead of angular-data-1.4.2.js in your plunker and it appeared to work.

**Comment by Hypercubed** [comment]
Ahhh... I was using master.  With angular-data-1.5.3.js create, inject, and get are all working as I would expect:  http://plnkr.co/edit/UJlL7U?p=preview

Thank you.
