### ISSUE TITLE
destroy requires an item to be found in the store?

### ISSUE THREAD

**Issue by dtheodor** [jmdobry/angular-data#301]
I am calling `MyObject.destroy(id)` and getting this error:
`type: "RuntimeError", message: "DS.destroy(myobject, 104[, options]): id: "104" not found!"`

Why does angular-data require the object to exist in the store in the first place? I only want to call `DELETE /api/object/104`, I don't need to load the object to do that.

This is with angular-data version `1.5.3`

**Comment by jmdobry** [comment]
In 2.x, the item will not be required to be in the store. Since changing this in 1.x would be a breaking change at this point (which I can't do) and it's already solved in 2.x, I'm going to consider this case closed. Until you switch to 2.x (it's in beta), here are some ways around it.

```js
// Check for it first
if (DS.get('user', 5)) {
  DS.destroy('user', 5);
}

// Only call destroy on items already in the store
user.DSDestroy();

// Add a new static method
DS.myDestroy = function (resourceName, id, options) {
  if (DS.get(resourceName, id)) {
    return DS.destroy(resourceName, id, options);
  } else {
    var deferred = $q.defer();
    deferred.resolve();
    return deferred.promise;
};
```

**Comment by dtheodor** [comment]
Ok, thanks.
